# -*- coding: utf-8 -*-
"""ML_Lab_0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XrQcZ5dOSNFzs4t5iZqm91I5rmCWv18j
"""

import pandas as pd
df=pd.DataFrame({
    "ÜSN":[21,22,23,24,25],
    "Name":["Sam","Ram","Dam","rahul","rakshith"],
    "Marks":[45,78,24,90,60]
})
df

from sklearn.datasets import load_diabetes
dia=load_diabetes()
df=pd.DataFrame(dia.data,columns=dia.feature_names)
df

filepath="/content/sample_sales_data.csv"
df=pd.read_csv(filepath)
df.head()

df=pd.read_csv("/content/Dataset of Diabetes .csv")
df.head()

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt

# Define the tickers and date range
tickers = ["HDFCBANK.NS", "ICICIBANK.NS", "KOTAKBANK.NS"]
start_date = "2024-01-01"
end_date = "2024-12-30"

# Download the data
data = yf.download(tickers, start=start_date, end=end_date)

# Check the structure of the downloaded data
print(data.head())  # Print the first few rows to see the column names

# Extract closing prices (if 'Adj Close' doesn't exist, fall back to 'Close')
closing_prices = data["Close"]

# Handle missing values by forward filling
closing_prices = closing_prices.ffill()

# Calculate daily returns
daily_returns = closing_prices.pct_change()

# Calculate 50-day moving average
moving_average = closing_prices.rolling(window=50).mean()

# Plotting
plt.figure(figsize=(12, 6))

# Closing Prices and 50-day Moving Average
plt.subplot(2, 1, 1)
for ticker in tickers:
    plt.plot(closing_prices.index, closing_prices[ticker], label=f"{ticker} Closing Price")
    plt.plot(moving_average.index, moving_average[ticker], label=f"{ticker} 50-Day MA", linestyle="--")
plt.title("Closing Prices of HDFC Bank, ICICI Bank, and Kotak Mahindra Bank with 50-Day Moving Average")
plt.xlabel("Date")
plt.ylabel("Closing Price")
plt.legend()

# Daily Returns
plt.subplot(2, 1, 2)
for ticker in tickers:
    plt.plot(daily_returns.index, daily_returns[ticker], label=ticker)
plt.title("Daily Returns of HDFC Bank, ICICI Bank, and Kotak Mahindra Bank")
plt.xlabel("Date")
plt.ylabel("Daily Return")
plt.legend()

plt.tight_layout()
plt.show()

